payum:
    security:
        token_storage:
            App\Entity\Payment\Token: { doctrine: orm }

    storages:
        App\Entity\Payment\Payment:
            doctrine: orm
#            custom: App\Classes\Payment\Storage

    gateways:
        offline:
            factory: offline