payum:
    security:
        token_storage:
            App\Entity\Payment\Token: { doctrine: orm }

    storages:
        App\Entity\Payment\Payment: { doctrine: orm }

    gateways:
        offline:
            factory: offline